MyApp/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('TrangChu/',include('TrangChu.urls'))
]

TrangChu/urls.py
from django.contrib import admin
from django.urls import path,include
from TrangChu import views

app_name = 'TrangChu'
urlpatterns = [
    path('', views.trangchu,name='trangchu'),
    path('student/', views.student,name='student'),
    path('teacher/', views.teacher,name='teacher'),
    path('login/', views.login,name='edit'),
    path('edit/', views.edit,name='login'),

]

TrangChu/models.py
from django.db import models

# Create your models here.

TrangChu/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def trangchu(request):
    return render(request, 'TrangChu.html')


def student(request):
    return render(request, 'SinhVien.html')


def teacher(request):
    return render(request, 'GiaoVien.html')


def login(request):
    return render(request, 'DangNhap.html')


def edit(request):
    return render(request, 'index4.html')

TrangChu/templates/DangNhap.html
<!DOCTYPE html>
<html>
<head>
    <title>Login Form</title>
</head>
<body>
    <h2>Đăng nhập quản lý</h2><br>
    <div class="login">
    <form id="login" >
        <label><b>Tài khoản
        </b>
        </label>
        <input type="text" name="Uname" id="Uname" placeholder="Tài khoản">
        <br><br>
        <label><b>Mật khẩu
        </b>
        </label>
        <input type="Mật khẩu" name="Pass" id="Pass" placeholder="Password">
        <br><br>
        <h2><a href="{% url 'TrangChu:edit' %}">Đăng nhập</a></h2>
        <br><br>
         <h2><a href="{% url 'TrangChu:trangchu' %}">Quay lại trang chủ</a></h2>
    </form>
</div>
</body>
</html>

TrangChu/templates/SinhVien.html
<!DOCTYPE html>
<html>
<head>
    <title>STUDENT</title>
    <style>
        .header{
            background-color: aquamarine;
            text-align: center;
        }

    </style>
</head>
<body>
    <div class="header"><h1>Thời khóa biểu sinh viên</h1></div>
<h1>Lớp k63a1</h1>
    <table border="1" cellspacing="0" align="center">
        <tr>
            <td align="center" height="50"
                width="100">
                <br>
                    <b>Thứ/Tiết</b>
                </br>
            </td>
            <td align="center" height="50"
                width="100">
                <b>I<br>7:00-9:00</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>II<br>9:10-11:10</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>III<br>11:10-12:00</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>12:00-12:40</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>IV<br>12:40-1:30</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>V<br>1:30-2:20</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>VI<br>2:20-3:10</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>VII<br>3:10-4:00</b>
            </td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 2</b></td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td rowspan="6" align="center" height="50">
            </td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">THCS</td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 3</b>
            </td>
            <td colspan="3" align="center"
                height="50">Thực hành
            </td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">SPORTS</td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 4</b>
            </td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">THCS</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">ENG</td>
           <td align="center" height="50">THCS</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">ENG</td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 5</b>
            </td>
            <td align="center" height="50">THCS</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">GTS</td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 6</b>
            </td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">THCS</td>
        </tr>

    </table>
<h1>Lớp k63a2</h1>
    <table border="1" cellspacing="0" align="center">
        <tr>
            <td align="center" height="50"
                width="100">
                <br>
                    <b>Thứ/Tiết</b>
                </br>
            </td>
            <td align="center" height="50"
                width="100">
                <b>I<br>7:00-9:00</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>II<br>9:10-11:10</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>III<br>11:10-12:00</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>12:00-12:40</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>IV<br>12:40-1:30</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>V<br>1:30-2:20</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>VI<br>2:20-3:10</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>VII<br>3:10-4:00</b>
            </td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 2</b></td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td rowspan="6" align="center" height="50">
            </td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">THCS</td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 3</b>
            </td>
            <td colspan="3" align="center"
                height="50">Thực hành
            </td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">SPORTS</td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 4</b>
            </td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">THCS</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">ENG</td>
           <td align="center" height="50">THCS</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">ENG</td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 5</b>
            </td>
            <td align="center" height="50">THCS</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">GTS</td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 6</b>
            </td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">THCS</td>
        </tr>

    </table>
<h1>Lớp k63a3</h1>
    <table border="1" cellspacing="0" align="center">
        <tr>
            <td align="center" height="50"
                width="100">
                <br>
                    <b>Thứ/Tiết</b>
                </br>
            </td>
            <td align="center" height="50"
                width="100">
                <b>I<br>7:00-9:00</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>II<br>9:10-11:10</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>III<br>11:10-12:00</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>12:00-12:40</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>IV<br>12:40-1:30</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>V<br>1:30-2:20</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>VI<br>2:20-3:10</b>
            </td>
            <td align="center" height="50"
                width="100">
                <b>VII<br>3:10-4:00</b>
            </td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 2</b></td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td rowspan="6" align="center" height="50">
            </td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">THCS</td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 3</b>
            </td>
            <td colspan="3" align="center"
                height="50">Thực hành
            </td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">SPORTS</td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 4</b>
            </td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">THCS</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">ENG</td>
           <td align="center" height="50">THCS</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">ENG</td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 5</b>
            </td>
            <td align="center" height="50">THCS</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">GTS</td>
        </tr>
        <tr>
            <td align="center" height="50">
                <b>Thứ 6</b>
            </td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">GTS</td>
            <td align="center" height="50">ENG</td>
            <td align="center" height="50">CSDL</td>
            <td align="center" height="50">THCS</td>
        </tr>

    </table>


</body>

</html>

TrangChu/templates/TrangChu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trang chu</title>
    <style>
        a{
    text-decoration: none;}
    </style>
</head>
<body> <h1 style="text-align: center; text-decoration: none;: none"><a  href="{% url 'TrangChu:login' %}">Đăng nhập</a></h1>
    <h1><a href="{% url 'TrangChu:student' %}">Thời khóa biểu sinh viên</a></h1>
 <h1><a href="{% url 'TrangChu:teacher' %}">Thời khóa biểu giáo viên</a></h1>

</body>
</html>

TrangChu/templates/index4.html
<!DOCTYPE html>
<html>
   <head>
      <title>Chỉnh sửa</title>
   </head>
   <body>
      <h1>Danh sách các thời khóa biểu</h1>
      <ol type = "1">
          <li>Thời khóa biểu lớp k63a1 <button type="button">Xóa</button><button type="button">Chỉnh sửa</button><button type="button">Thêm mới</button></li>
          <li>Thời khóa biểu lớp k63a2 <button type="button">Xóa</button><button type="button">Chỉnh sửa</button><button type="button">Thêm mới</button></li>
          <li>Thời khóa biểu lớp k63a3 <button type="button">Xóa</button><button type="button">Chỉnh sửa</button><button type="button">Thêm mới</button></li>
          <li>Thời khóa biểu lớp k63a4<button type="button">Xóa</button><button type="button">Chỉnh sửa</button><button type="button">Thêm mới</button></li>
       

      </ol>
   </body>
</html>